name: todos
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^1.1.0

dev_dependencies: 
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  mockito: ^5.4.2
  test: ^1.24.1

flutter: 
  uses-material-design: true

